# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


credit_card_charges = [{"id": 9923,
                        "created": 1389618241,
                        "paid": true,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 1},
                      {"id": 9924,
                        "created": 1389618242,
                        "paid": true,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 1},
                      {"id": 9925,
                        "created": 1389618243,
                        "paid": true,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 1},
                      {"id": 9926,
                        "created": 1389618244,
                        "paid": true,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 1},
                      {"id": 9927,
                        "created": 1389618245,
                        "paid": true,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 1},
                      {"id": 9928,
                        "created": 1389618246,
                        "paid": true,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 2},
                      {"id": 9929,
                        "created": 1389618247,
                        "paid": true,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 2},
                      {"id": 9930,
                        "created": 1389618248,
                        "paid": true,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 2},                     
                      {"id": 9931,
                        "created": 1389618249,
                        "paid": true,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 3},                     
                      {"id": 9932,
                        "created": 1389618250,
                        "paid": true,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 4},
                      {"id": 9933,
                        "created": 1389618251,
                        "paid": false,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 3},
                      {"id": 9934,
                        "created": 1389618252,
                        "paid": false,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 3},
                      {"id": 9935,
                        "created": 1389618253,
                        "paid": false,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 3},
                      {"id": 9936,
                        "created": 1389618254,
                        "paid": false,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 4},
                      {"id": 9937,
                        "created": 1389618255,
                        "paid": false,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 4},
                      {"id": 9938,
                        "created": 1389618256,
                        "paid": nil,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 1},
                      {"id": 9939,
                        "created": 1389618257,
                        "paid": nil,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 1},
                      {"id": 9940,
                        "created": 1389618258,
                        "paid": nil,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 1},
                      {"id": 9941,
                        "created": 1389618259,
                        "paid": nil,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 2},
                      {"id": 9942,
                        "created": 1389618260,
                        "paid": nil,
                        "amount": 4900,
                        "currency": "usd",
                        "refunded": false,
                        "customer_id": 2}]

customers = [["Johny", "Flow"],
              ["Raj", "Jamins"],
              ["Andrew", "Chung"], 
              ["Mike", "Smith"]
            ]





credit_card_charges.each do |charge|
  CreditCardCharge.create!(records: charge)
end

customers.each do |first_name, last_name|
  Customer.create(first_name: first_name, last_name: last_name)
end
